#-----------------------------------------------------------------
#Para espeleo_robo:                                              |
#-----------------------------------------------------------------
# mass : 26.42 # espeleo mass in [kg]
# kpr :  66    # 66:1 
# kt : 24.3e-3 #torque constant [N.m/A]
# kw :  41.15  # [rad.V/s] -> 393rpm ~ 41.15rad/s
# kred : 0.75   #[%]
# gravity : 9.80665 #m/s²
#-----------------------------------------------------------------
#-----------------------------------------------------------------
#Para Husky:                                              |
#-----------------------------------------------------------------
# mass : 50
# kpr :  78.71   # 78.71:1 
# kt : 44.488e-3 #torque constant [N.m/A]
# kw :  19.7  # [rad.V/s] -> 393rpm ~ 41.15rad/s
# kred : 0.7   #[%]
# gravity : 9.80665 #m/s²
#-----------------------------------------------------------------
#-----------------------------------------------------------------
#Para Pioneer:                                              |
#-----------------------------------------------------------------
mass :  24.6
kpr :  38.3   
kt : 23.0e-3 #torque constant [N.m/A]
kw :  40.6  # [rad.V/s] -> 393rpm ~ 41.15rad/s
kred : 0.7   #[%]
gravity : 9.80665 #m/s²
#-----------------------------------------------------------------